### ISSUE TITLE
GHA Windows SQLite linking

### ISSUE THREAD

**Issue by bsikar** [bsikar/pos-system#18]
With GitHub Actions when adding Windows to the action I get a linking error because `sqlite3.lib` does not exist, but I cannot seem to fix the linking issue.

**Comment by bsikar** [comment]
```yml
   - name: Fit SQLite on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install sqlite -y
        cd C:\ProgramData\chocolatey\lib\SQLite\tools
        & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\Hostx64\x64\lib.exe' /DEF:sqlite3.def /OUT:sqlite3.lib /MACHINE:x64
```
this will make `sqlite3.lib`
